### ISSUE TITLE
wishlist: offer options for smaller data bundles

### ISSUE THREAD

**Issue by mlc** [js-joda/js-joda-timezone#67]
Because of moment/moment-timezone#697, the timezone data upon which `js-joda-timezone` relies has grown massively in size recently, and therefore so has `js-joda-timezone` itself.

| version | dist/js-joda-timezone.min.js | gzip -9 |
| --- | --- | --- |
| 2.0.1 | 186973 bytes | 25331 bytes |
| 2.0.2 | 931347 bytes | 36084 bytes |

`moment-timezone` is [now offering](https://github.com/moment/moment-timezone/tree/develop/builds) builds of the package with some of the data removed if it is not relevant for timestamps within ±5 years or so of the present. It would be good if `js-joda-timzeone` could copy this and offer smaller builds of the package for use cases where this makes sense.

**Comment by pithu** [comment]
Because we are using the tz data files from moment-timezone it shouldn't be so difficult to use the minimized versions. We are open for PR.

**Comment by JKillian** [comment]
Hey @mlc I ran in to the same issue as you, so I put up a PR, https://github.com/js-joda/js-joda-timezone/pull/73, to offer some alternative builds! Feel free to give it a look and comment if you ahve any thoughts
