### ISSUE TITLE
How to use with TypeScript

### ISSUE THREAD

**Issue by afr1983** [js-joda/js-joda-timezone#7]
I am using js-joda in Typescript, however I need the timezone support provided by this extension. How do I use it with Typescript?

**Comment by pithu** [comment]
Hello @afr1983 

well i am not a typescript user but i would guess its the same as for es6

```
import jsJoda from 'js-joda'
import jsJodaTimezone from 'js-joda-timezone'

jsJoda.use(jsJodaTimezone)

const {LocalDateTime, ZoneId, ZonedDateTime } = jsJoda;
```

Does this help ?

**Comment by ianp** [comment]
It's a bit of a mess because `js-joda` wants to play silly dynamic tricks with require and TypeScript _really_ doesn't like this, so you have to import the types that you are using and require the timezone module separately, like this:

```ts
import {LocalDate, ZonedDateTime} from 'js-joda'
const joda = require('js-joda').use(require('js-joda-timezone'))

const getDate = (s: string): LocalDate => {
  // ...
  return LocalDate.of(year, month, day)
}
```

Note that this will mess up autocompletion in most/all IDEs, so you may want to comment out the `.use(…)` portion of that require chain while you are editing code.

Note that if you do want to import all of the types and use them prefixed then you need to use `import * as …` because there is no default export.

**Comment by afr1983** [comment]
@ianp That did the trick, thanks! I was trying to figure out how to import AND use in the same line, would never work.

**Comment by pithu** [comment]
The reason for your problems are probably that the `use` method is missing in the `js-joda` typescript definition. I will add it in the next release.

**Comment by Dyktus** [comment]
@pithu Sorry for opening this topic again but it would be good to add your last post to README.md because it took me some time to find this solution :)

**Comment by pithu** [comment]
Hi @Dyktus 

thanks for reporting, well i guess you are right and we should document it and it would be nice to get rid of the `require` hack.,

I played around a bit with typescript, one possible solution could be to change the export of  `js-joda-timezone` (and all other js-joda-plugins) to a named export. So the code would look like:

```
import { use, ZonedDateTime, ZoneId } from 'js-joda'
import { plug } from 'js-joda-timezone';

use(plug)

const zdt = ZonedDateTime.now(ZoneId.of('America/New_York'))
```

Another solution could be to move the plugin setup into the plugin internal code and hide from the code using it. I have the feeling that most coders are confused from the plugin solution anyway. so code could simply look like:

```
import { ZonedDateTime, ZoneId } from 'js-joda'
import 'js-joda-timezone';

const zdt = ZonedDateTime.now(ZoneId.of('America/New_York'))

``` 

not sure if that works but i will try it out.

**Comment by pithu** [comment]
Ok, i checked both approaches, both are working.

I vote for the later, because its more convenient. @phueper what is your opinion ?

**Comment by phueper** [comment]
I like the second approach much better as well...

Maybe, even nicer would be something like this, if possible:
```
import  { ZonedDateTime, ZoneId } from  'js-joda-timezone';

const zdt = ZonedDateTime.now(ZoneId.of('America/New_York'))
```

That would keep users from having to import joda and the plugin separately ... i don't know if this can work, but it would be nice...  also for plugins like `-extra` that add new classes to the export maybe?

**Comment by pithu** [comment]
Great idea, but i am not sure how could make it. `js-joda-timezone` is injecting the `ZoneRulesProvider` and exporting nothing. So i would have to somehow export all classes and typescript definitions from js-joda here again. 

Might be interesting to think about for later, for now i just take the simple way.

**Comment by pithu** [comment]
I just pushed the new version `@1.3.0`. With that version the `use(plug)` thingy is not required anymore, so it should work fine with typescript. 

btw: in the repo https://github.com/js-joda/js-joda-examples.git you can find some examples how to use js-joda together with js-joda-timezone. There is also a typescript example.
