### ISSUE TITLE
How to load own tzdb data?

### ISSUE THREAD

**Issue by jrsearles** [js-joda/js-joda-timezone#72]
I see that there is an "empty" build of this library without tzdb data loaded. I've stripped out data from moment-timezone to only the time zones I will be supporting, however it's not clear to me how to use the empty build and load my own dataset and bootstrap the library. Any tips?

**Comment by jrsearles** [comment]
I think i figured it out. Looks like methods are added to `ZoneRulesProvider` (loadTzdbData) that can be used to load customized data.

**Comment by pithu** [comment]
Exactly, that's the way to do it
