### ISSUE TITLE
Warning about incorrect peer dependency

### ISSUE THREAD

**Issue by neuronaut** [js-joda/js-joda-timezone#76]
I'm getting the following warning when I install dependencies ever since updating to @js-joda/core 2.x:

`warning " > @js-joda/timezone@2.2.0" has incorrect peer dependency "@js-joda/core@^1.11.0"`

It seems that the peer dependency in @js-joda/timezone needs to be updated. (Or should I not be using @js-joda/timezone 2.x with js-joda/core 2.x?)

**Comment by pithu** [comment]
!This package is deprecated!

please use these versions: https://github.com/js-joda/js-joda#js-joda-is-now-a-mono-repo

**Comment by neuronaut** [comment]
That's exactly what I'm using. My dependency in package.json is declared like this:

```
"@js-joda/core": "^2.0.0",
"@js-joda/timezone": "^2.0.2",
```

And my requires are like this:

```
const { ZonedDateTime } = require('@js-code/core');
require('@js-joda/timezone');
```

Yet I still get the above warning. Which is why I filed the issue as it was unexpected that I'd get a warning once using both js-joda/core and js-joda/timezone the same way (i.e. the mono-repo style).

**Comment by neuronaut** [comment]
After some poking around I see what I did wrong -- I filed the issue in the wrong place. Why didn't you just say so? You made it sound like I was doing the wrong thing in my code.
